// Code generated by ent, DO NOT EDIT.

package ent

import (
	"match-me/ent/schema"
	"match-me/ent/user"
	"match-me/ent/userphoto"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[3].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = func() func(string) error {
		validators := userDescFirstName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(first_name string) error {
			for _, fn := range fns {
				if err := fn(first_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[4].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescIsOnline is the schema descriptor for is_online field.
	userDescIsOnline := userFields[7].Descriptor()
	// user.DefaultIsOnline holds the default value on creation for the is_online field.
	user.DefaultIsOnline = userDescIsOnline.Default.(bool)
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[8].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = func() func(int) error {
		validators := userDescAge.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(age int) error {
			for _, fn := range fns {
				if err := fn(age); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescGender is the schema descriptor for gender field.
	userDescGender := userFields[9].Descriptor()
	// user.GenderValidator is a validator for the "gender" field. It is called by the builders before save.
	user.GenderValidator = userDescGender.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	userphotoFields := schema.UserPhoto{}.Fields()
	_ = userphotoFields
	// userphotoDescPhotoURL is the schema descriptor for photo_url field.
	userphotoDescPhotoURL := userphotoFields[1].Descriptor()
	// userphoto.PhotoURLValidator is a validator for the "photo_url" field. It is called by the builders before save.
	userphoto.PhotoURLValidator = userphotoDescPhotoURL.Validators[0].(func(string) error)
	// userphotoDescOrder is the schema descriptor for order field.
	userphotoDescOrder := userphotoFields[2].Descriptor()
	// userphoto.OrderValidator is a validator for the "order" field. It is called by the builders before save.
	userphoto.OrderValidator = userphotoDescOrder.Validators[0].(func(int) error)
	// userphotoDescID is the schema descriptor for id field.
	userphotoDescID := userphotoFields[0].Descriptor()
	// userphoto.DefaultID holds the default value on creation for the id field.
	userphoto.DefaultID = userphotoDescID.Default.(func() uuid.UUID)
}
