// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"match-me/ent/predicate"
	"match-me/ent/user"
	"match-me/ent/userphoto"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserPhotoUpdate is the builder for updating UserPhoto entities.
type UserPhotoUpdate struct {
	config
	hooks    []Hook
	mutation *UserPhotoMutation
}

// Where appends a list predicates to the UserPhotoUpdate builder.
func (_u *UserPhotoUpdate) Where(ps ...predicate.UserPhoto) *UserPhotoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPhotoURL sets the "photo_url" field.
func (_u *UserPhotoUpdate) SetPhotoURL(v string) *UserPhotoUpdate {
	_u.mutation.SetPhotoURL(v)
	return _u
}

// SetNillablePhotoURL sets the "photo_url" field if the given value is not nil.
func (_u *UserPhotoUpdate) SetNillablePhotoURL(v *string) *UserPhotoUpdate {
	if v != nil {
		_u.SetPhotoURL(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *UserPhotoUpdate) SetOrder(v int) *UserPhotoUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *UserPhotoUpdate) SetNillableOrder(v *int) *UserPhotoUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *UserPhotoUpdate) AddOrder(v int) *UserPhotoUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserPhotoUpdate) SetUserID(v uuid.UUID) *UserPhotoUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserPhotoUpdate) SetNillableUserID(v *uuid.UUID) *UserPhotoUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserPhotoUpdate) SetUser(v *User) *UserPhotoUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserPhotoMutation object of the builder.
func (_u *UserPhotoUpdate) Mutation() *UserPhotoMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserPhotoUpdate) ClearUser() *UserPhotoUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserPhotoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserPhotoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserPhotoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserPhotoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserPhotoUpdate) check() error {
	if v, ok := _u.mutation.PhotoURL(); ok {
		if err := userphoto.PhotoURLValidator(v); err != nil {
			return &ValidationError{Name: "photo_url", err: fmt.Errorf(`ent: validator failed for field "UserPhoto.photo_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Order(); ok {
		if err := userphoto.OrderValidator(v); err != nil {
			return &ValidationError{Name: "order", err: fmt.Errorf(`ent: validator failed for field "UserPhoto.order": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserPhoto.user"`)
	}
	return nil
}

func (_u *UserPhotoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userphoto.Table, userphoto.Columns, sqlgraph.NewFieldSpec(userphoto.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PhotoURL(); ok {
		_spec.SetField(userphoto.FieldPhotoURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(userphoto.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(userphoto.FieldOrder, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userphoto.UserTable,
			Columns: []string{userphoto.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userphoto.UserTable,
			Columns: []string{userphoto.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userphoto.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserPhotoUpdateOne is the builder for updating a single UserPhoto entity.
type UserPhotoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserPhotoMutation
}

// SetPhotoURL sets the "photo_url" field.
func (_u *UserPhotoUpdateOne) SetPhotoURL(v string) *UserPhotoUpdateOne {
	_u.mutation.SetPhotoURL(v)
	return _u
}

// SetNillablePhotoURL sets the "photo_url" field if the given value is not nil.
func (_u *UserPhotoUpdateOne) SetNillablePhotoURL(v *string) *UserPhotoUpdateOne {
	if v != nil {
		_u.SetPhotoURL(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *UserPhotoUpdateOne) SetOrder(v int) *UserPhotoUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *UserPhotoUpdateOne) SetNillableOrder(v *int) *UserPhotoUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *UserPhotoUpdateOne) AddOrder(v int) *UserPhotoUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserPhotoUpdateOne) SetUserID(v uuid.UUID) *UserPhotoUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserPhotoUpdateOne) SetNillableUserID(v *uuid.UUID) *UserPhotoUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserPhotoUpdateOne) SetUser(v *User) *UserPhotoUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserPhotoMutation object of the builder.
func (_u *UserPhotoUpdateOne) Mutation() *UserPhotoMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserPhotoUpdateOne) ClearUser() *UserPhotoUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserPhotoUpdate builder.
func (_u *UserPhotoUpdateOne) Where(ps ...predicate.UserPhoto) *UserPhotoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserPhotoUpdateOne) Select(field string, fields ...string) *UserPhotoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserPhoto entity.
func (_u *UserPhotoUpdateOne) Save(ctx context.Context) (*UserPhoto, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserPhotoUpdateOne) SaveX(ctx context.Context) *UserPhoto {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserPhotoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserPhotoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserPhotoUpdateOne) check() error {
	if v, ok := _u.mutation.PhotoURL(); ok {
		if err := userphoto.PhotoURLValidator(v); err != nil {
			return &ValidationError{Name: "photo_url", err: fmt.Errorf(`ent: validator failed for field "UserPhoto.photo_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Order(); ok {
		if err := userphoto.OrderValidator(v); err != nil {
			return &ValidationError{Name: "order", err: fmt.Errorf(`ent: validator failed for field "UserPhoto.order": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserPhoto.user"`)
	}
	return nil
}

func (_u *UserPhotoUpdateOne) sqlSave(ctx context.Context) (_node *UserPhoto, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userphoto.Table, userphoto.Columns, sqlgraph.NewFieldSpec(userphoto.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserPhoto.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userphoto.FieldID)
		for _, f := range fields {
			if !userphoto.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userphoto.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PhotoURL(); ok {
		_spec.SetField(userphoto.FieldPhotoURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(userphoto.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(userphoto.FieldOrder, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userphoto.UserTable,
			Columns: []string{userphoto.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userphoto.UserTable,
			Columns: []string{userphoto.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserPhoto{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userphoto.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
