// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"match-me/ent/predicate"
	"match-me/ent/userinteraction"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserInteractionDelete is the builder for deleting a UserInteraction entity.
type UserInteractionDelete struct {
	config
	hooks    []Hook
	mutation *UserInteractionMutation
}

// Where appends a list predicates to the UserInteractionDelete builder.
func (_d *UserInteractionDelete) Where(ps ...predicate.UserInteraction) *UserInteractionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserInteractionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserInteractionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserInteractionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userinteraction.Table, sqlgraph.NewFieldSpec(userinteraction.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserInteractionDeleteOne is the builder for deleting a single UserInteraction entity.
type UserInteractionDeleteOne struct {
	_d *UserInteractionDelete
}

// Where appends a list predicates to the UserInteractionDelete builder.
func (_d *UserInteractionDeleteOne) Where(ps ...predicate.UserInteraction) *UserInteractionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserInteractionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userinteraction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserInteractionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
