// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"match-me/ent/user"
	"match-me/ent/userphoto"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserPhotoCreate is the builder for creating a UserPhoto entity.
type UserPhotoCreate struct {
	config
	mutation *UserPhotoMutation
	hooks    []Hook
}

// SetPhotoURL sets the "photo_url" field.
func (_c *UserPhotoCreate) SetPhotoURL(v string) *UserPhotoCreate {
	_c.mutation.SetPhotoURL(v)
	return _c
}

// SetPublicID sets the "public_id" field.
func (_c *UserPhotoCreate) SetPublicID(v string) *UserPhotoCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetOrder sets the "order" field.
func (_c *UserPhotoCreate) SetOrder(v int) *UserPhotoCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserPhotoCreate) SetUserID(v uuid.UUID) *UserPhotoCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UserPhotoCreate) SetID(v uuid.UUID) *UserPhotoCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserPhotoCreate) SetNillableID(v *uuid.UUID) *UserPhotoCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserPhotoCreate) SetUser(v *User) *UserPhotoCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserPhotoMutation object of the builder.
func (_c *UserPhotoCreate) Mutation() *UserPhotoMutation {
	return _c.mutation
}

// Save creates the UserPhoto in the database.
func (_c *UserPhotoCreate) Save(ctx context.Context) (*UserPhoto, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPhotoCreate) SaveX(ctx context.Context) *UserPhoto {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPhotoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPhotoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserPhotoCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := userphoto.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPhotoCreate) check() error {
	if _, ok := _c.mutation.PhotoURL(); !ok {
		return &ValidationError{Name: "photo_url", err: errors.New(`ent: missing required field "UserPhoto.photo_url"`)}
	}
	if v, ok := _c.mutation.PhotoURL(); ok {
		if err := userphoto.PhotoURLValidator(v); err != nil {
			return &ValidationError{Name: "photo_url", err: fmt.Errorf(`ent: validator failed for field "UserPhoto.photo_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "UserPhoto.public_id"`)}
	}
	if _, ok := _c.mutation.Order(); !ok {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required field "UserPhoto.order"`)}
	}
	if v, ok := _c.mutation.Order(); ok {
		if err := userphoto.OrderValidator(v); err != nil {
			return &ValidationError{Name: "order", err: fmt.Errorf(`ent: validator failed for field "UserPhoto.order": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserPhoto.user_id"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserPhoto.user"`)}
	}
	return nil
}

func (_c *UserPhotoCreate) sqlSave(ctx context.Context) (*UserPhoto, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPhotoCreate) createSpec() (*UserPhoto, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPhoto{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userphoto.Table, sqlgraph.NewFieldSpec(userphoto.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PhotoURL(); ok {
		_spec.SetField(userphoto.FieldPhotoURL, field.TypeString, value)
		_node.PhotoURL = value
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(userphoto.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(userphoto.FieldOrder, field.TypeInt, value)
		_node.Order = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userphoto.UserTable,
			Columns: []string{userphoto.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserPhotoCreateBulk is the builder for creating many UserPhoto entities in bulk.
type UserPhotoCreateBulk struct {
	config
	err      error
	builders []*UserPhotoCreate
}

// Save creates the UserPhoto entities in the database.
func (_c *UserPhotoCreateBulk) Save(ctx context.Context) ([]*UserPhoto, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPhoto, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPhotoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPhotoCreateBulk) SaveX(ctx context.Context) []*UserPhoto {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPhotoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPhotoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
