// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"match-me/ent/user"
	"match-me/ent/userinteraction"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserInteractionCreate is the builder for creating a UserInteraction entity.
type UserInteractionCreate struct {
	config
	mutation *UserInteractionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserInteractionCreate) SetUserID(v uuid.UUID) *UserInteractionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTargetUserID sets the "target_user_id" field.
func (_c *UserInteractionCreate) SetTargetUserID(v uuid.UUID) *UserInteractionCreate {
	_c.mutation.SetTargetUserID(v)
	return _c
}

// SetInteractionType sets the "interaction_type" field.
func (_c *UserInteractionCreate) SetInteractionType(v userinteraction.InteractionType) *UserInteractionCreate {
	_c.mutation.SetInteractionType(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserInteractionCreate) SetCreatedAt(v time.Time) *UserInteractionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserInteractionCreate) SetNillableCreatedAt(v *time.Time) *UserInteractionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserInteractionCreate) SetExpiresAt(v time.Time) *UserInteractionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UserInteractionCreate) SetNillableExpiresAt(v *time.Time) *UserInteractionCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *UserInteractionCreate) SetMetadata(v map[string]interface{}) *UserInteractionCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UserInteractionCreate) SetID(v uuid.UUID) *UserInteractionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserInteractionCreate) SetNillableID(v *uuid.UUID) *UserInteractionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserInteractionCreate) SetUser(v *User) *UserInteractionCreate {
	return _c.SetUserID(v.ID)
}

// SetTargetUser sets the "target_user" edge to the User entity.
func (_c *UserInteractionCreate) SetTargetUser(v *User) *UserInteractionCreate {
	return _c.SetTargetUserID(v.ID)
}

// Mutation returns the UserInteractionMutation object of the builder.
func (_c *UserInteractionCreate) Mutation() *UserInteractionMutation {
	return _c.mutation
}

// Save creates the UserInteraction in the database.
func (_c *UserInteractionCreate) Save(ctx context.Context) (*UserInteraction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserInteractionCreate) SaveX(ctx context.Context) *UserInteraction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserInteractionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserInteractionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserInteractionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userinteraction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := userinteraction.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserInteractionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserInteraction.user_id"`)}
	}
	if _, ok := _c.mutation.TargetUserID(); !ok {
		return &ValidationError{Name: "target_user_id", err: errors.New(`ent: missing required field "UserInteraction.target_user_id"`)}
	}
	if _, ok := _c.mutation.InteractionType(); !ok {
		return &ValidationError{Name: "interaction_type", err: errors.New(`ent: missing required field "UserInteraction.interaction_type"`)}
	}
	if v, ok := _c.mutation.InteractionType(); ok {
		if err := userinteraction.InteractionTypeValidator(v); err != nil {
			return &ValidationError{Name: "interaction_type", err: fmt.Errorf(`ent: validator failed for field "UserInteraction.interaction_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserInteraction.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserInteraction.user"`)}
	}
	if len(_c.mutation.TargetUserIDs()) == 0 {
		return &ValidationError{Name: "target_user", err: errors.New(`ent: missing required edge "UserInteraction.target_user"`)}
	}
	return nil
}

func (_c *UserInteractionCreate) sqlSave(ctx context.Context) (*UserInteraction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserInteractionCreate) createSpec() (*UserInteraction, *sqlgraph.CreateSpec) {
	var (
		_node = &UserInteraction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userinteraction.Table, sqlgraph.NewFieldSpec(userinteraction.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.InteractionType(); ok {
		_spec.SetField(userinteraction.FieldInteractionType, field.TypeEnum, value)
		_node.InteractionType = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userinteraction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(userinteraction.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(userinteraction.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userinteraction.UserTable,
			Columns: []string{userinteraction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userinteraction.TargetUserTable,
			Columns: []string{userinteraction.TargetUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TargetUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserInteractionCreateBulk is the builder for creating many UserInteraction entities in bulk.
type UserInteractionCreateBulk struct {
	config
	err      error
	builders []*UserInteractionCreate
}

// Save creates the UserInteraction entities in the database.
func (_c *UserInteractionCreateBulk) Save(ctx context.Context) ([]*UserInteraction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserInteraction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserInteractionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserInteractionCreateBulk) SaveX(ctx context.Context) []*UserInteraction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserInteractionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserInteractionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
