// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPhoto is the predicate function for userphoto builders.
type UserPhoto func(*sql.Selector)
