# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/matchme-server ./cmd/server"
bin = "tmp/matchme-server"
full_bin = ""
exclude_dir = ["tmp", "docs", "scripts", "migrations", "vendor", "templates", "node-gateway"]
include_ext = ["go"]
exclude_ext = ["md"]
delay = 1000
log = "stdout"
stop_on_error = true


[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
