// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString, Size: 50},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 30},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "is_online", Type: field.TypeBool, Default: false},
		{Name: "age", Type: field.TypeInt},
		{Name: "gender", Type: field.TypeString},
		{Name: "looking_for", Type: field.TypeJSON, Nullable: true},
		{Name: "interests", Type: field.TypeJSON, Nullable: true},
		{Name: "music_preferences", Type: field.TypeJSON, Nullable: true},
		{Name: "food_preferences", Type: field.TypeJSON, Nullable: true},
		{Name: "communication_style", Type: field.TypeString, Nullable: true},
		{Name: "prompts", Type: field.TypeJSON, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserPhotosColumns holds the columns for the "user_photos" table.
	UserPhotosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "photo_url", Type: field.TypeString},
		{Name: "order", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// UserPhotosTable holds the schema information for the "user_photos" table.
	UserPhotosTable = &schema.Table{
		Name:       "user_photos",
		Columns:    UserPhotosColumns,
		PrimaryKey: []*schema.Column{UserPhotosColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_photos_users_photos",
				Columns:    []*schema.Column{UserPhotosColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		UserPhotosTable,
	}
)

func init() {
	UserPhotosTable.ForeignKeys[0].RefTable = UsersTable
}
